spring:
  application:
    name: common-module
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/internetbank}

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8081}
  realm: ${KEYCLOAK_REALM:internetbank}

internal:
  api:
    key: uYuQ8lwlpZbVmZB4u8U8DWZJiLojIaGr